In [46]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import matplotlib.dates as mdates
import os
import glob
import re
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [2]:
#Constant variables
month = {
                'Jan' : '01',
                'Feb' : '02',
                'Mar' : '03',
                'May' : '04',
                'Apr' : '05',
                'Jun' : '06',
                'Jul' : '07',
                'Aug' : '08',
                'Sep' : '09',
                'Oct' : '10',
                'Nov' : '11',
                'Dec' : '12',  
}

# Use 2016-2019 Data to predict 2020's Gold Price

## import dataset

In [3]:
gold =pd.read_csv("./dataset/gld_price_data.csv")
gas =pd.read_csv("./dataset/natural_gas_data.csv")
oil = pd.read_csv('./dataset/crude_oil_eu_data.csv')
dolla = pd.read_csv('./dataset/dolla_index_data.csv')
etf = pd.read_csv('./dataset/etf_data.csv')
sil = pd.DataFrame(pd.read_csv('./dataset/silver_price_data.csv'), columns={'Date','USD'})
bit = pd.DataFrame(pd.read_csv('./dataset/bit_data.csv'), columns={'Date','Close'})

In [4]:
sil = sil[['Date','USD']]
bit = bit[['Date','Close']]

## data preprocessing

In [5]:
### daily data only
### df : list of dataframe , name : list of dataframe's value's name , color : list of data's color
df = [gold,gas,oil,dolla,etf,sil,bit]
columnName = ['gld_price', 'gas_price', 'oil_price','dolla_index','etf_index','silver_price','bitcoin_price']
color = ['red', 'green', 'blue', 'violet','purple','silver','gold']

In [6]:
### rename all data columns
for i in range(len(df)):
    df[i] = df[i].rename(columns={df[i].columns[0]:'date',df[i].columns[1]:columnName[i]})

In [7]:
### set date as index and join all data
data = df[0].set_index('date')
for i in range(len(df)):
    if i > 0:
        data = data.join(df[i].set_index('date'))

In [8]:
data

,gld_price,gas_price,oil_price,dolla_index,etf_index,silver_price,bitcoin_price
date,,,,,,,
2016-02-19,1231.15,1.83,31.66,113.9502,24.88,15.37,420.785004
2016-02-19,1267.00,1.83,31.66,113.9502,24.88,15.37,420.785004
2016-02-22,1211.00,1.86,33.59,113.8157,23.31,15.00,437.747986
2016-02-23,1221.35,1.85,31.90,114.1686,23.69,15.21,420.735992
2016-02-24,1250.75,1.85,31.50,114.163,24.24,15.32,424.954987
2016-02-25,1236.00,1.78,32.83,113.916,23.36,15.16,424.544006
2016-02-26,1226.50,1.78,35.76,114.365,21.67,15.17,432.152008
2016-02-29,1234.90,1.62,35.92,114.2359,22.59,14.75,437.696991
2016-03-01,1236.50,1.57,35.73,113.9208,21.97,14.99,435.122986
2016-03-02,1239.20,1.60,36.38,113.7902,22.00,14.82,423.989014
2016-03-03,1250.25,1.59,35.75,113.2419,23.51,14.97,421.651001
2016-03-04,1277.50,1.49,37.61,112.6317,22.31,15.43,410.938995
2016-03-07,1267.90,1.56,39.02,112.6166,22.08,15.66,414.321014
2016-03-09,1246.40,1.61,40.26,112.4212,22.31,15.27,414.859985
2016-03-10,1266.50,1.72,38.63,112.4122,23.14,15.27,417.131012
2016-03-11,1264.75,1.74,39.41,111.7351,21.90,15.50,421.690002
2016-03-14,1242.75,1.68,38.06,112.1613,21.14,15.60,416.437988
2016-03-15,1232.00,1.81,37.49,112.5466,19.70,15.32,416.829987
2016-03-16,1228.50,1.77,38.38,112.7674,20.03,15.29,417.010986
2016-03-17,1266.50,1.84,39.29,110.4412,18.99,15.73,420.621002
2016-03-18,1252.10,1.84,39.26,110.3961,18.15,15.94,409.548004
2016-03-21,1244.90,1.79,39.91,110.731,17.40,15.81,413.307007
2016-03-22,1252.50,1.79,40.54,110.7805,17.62,15.89,418.088989
2016-03-23,1217.60,1.79,38.84,111.5395,18.00,15.58,418.040985
2016-03-24,1221.00,1.78,38.33,111.8078,18.09,15.28,416.394012
2016-03-25,1221.00,1.78,.,111.7611,.,NaN,417.177002
2016-03-28,1221.00,1.78,38.33,111.3509,17.53,NaN,424.230988
2016-03-29,1226.00,1.77,36.75,111.3677,19.52,15.06,416.515991
2016-03-30,1236.25,1.87,36.75,110.2259,18.58,15.38,414.816010
2016-03-31,1237.00,1.98,36.75,109.9138,18.45,15.38,416.729004
...,...,...,...,...,...,...,...
2021-01-04,1943.20,NaN,NaN,NaN,NaN,NaN,31971.914063
2021-01-05,1940.35,NaN,NaN,NaN,NaN,NaN,33992.429688
2021-01-06,1931.95,NaN,NaN,NaN,NaN,NaN,36824.363281
2021-01-07,1920.10,NaN,NaN,NaN,NaN,NaN,39371.042969
2021-01-08,1862.90,NaN,NaN,NaN,NaN,NaN,40797.609375
2021-01-11,1847.25,NaN,NaN,NaN,NaN,NaN,35566.656250
2021-01-12,1841.25,NaN,NaN,NaN,NaN,NaN,33922.960938
2021-01-13,1858.85,NaN,NaN,NaN,NaN,NaN,37316.359375
2021-01-14,1841.75,NaN,NaN,NaN,NaN,NaN,39187.328125
2021-01-15,1839.00,NaN,NaN,NaN,NaN,NaN,36825.367188
2021-01-18,1833.05,NaN,NaN,NaN,NaN,NaN,36630.074219
2021-01-19,1834.70,NaN,NaN,NaN,NaN,NaN,36069.804688
2021-01-20,1856.60,NaN,NaN,NaN,NaN,NaN,35547.750000
2021-01-21,1862.10,NaN,NaN,NaN,NaN,NaN,30825.699219
2021-01-22,1852.70,NaN,NaN,NaN,NaN,NaN,33005.761719
2021-01-25,1856.85,NaN,NaN,NaN,NaN,NaN,32366.392578
2021-01-26,1856.60,NaN,NaN,NaN,NaN,NaN,32569.849609
2021-01-27,1843.00,NaN,NaN,NaN,NaN,NaN,30432.546875
2021-01-28,1853.70,NaN,NaN,NaN,NaN,NaN,31649.605469
2021-01-29,1863.80,NaN,NaN,NaN,NaN,NaN,34316.386719
2021-02-01,1862.95,NaN,NaN,NaN,NaN,NaN,33537.175781
2021-02-02,1833.10,NaN,NaN,NaN,NaN,NaN,35510.289063
2021-02-03,1835.45,NaN,NaN,NaN,NaN,NaN,37472.089844
2021-02-04,1785.90,NaN,NaN,NaN,NaN,NaN,36926.066406
2021-02-05,1802.95,NaN,NaN,NaN,NaN,NaN,38144.308594
2021-02-08,1835.25,NaN,NaN,NaN,NaN,NaN,46196.464844
2021-02-09,1839.60,NaN,NaN,NaN,NaN,NaN,46481.105469
2021-02-10,1842.65,NaN,NaN,NaN,NaN,NaN,44918.183594
2021-02-11,1840.10,NaN,NaN,NaN,NaN,NaN,47909.332031
2021-02-12,1816.35,NaN,NaN,NaN,NaN,NaN,47504.851563

In [9]:
data = data.replace('.', np.NaN)
data = data.dropna()

In [10]:
### convert index to datetime64
data = pd.DataFrame(data, index = np.array([np.datetime64(i) for i in data.index]))

In [11]:
### convert all data values to float
for i in data.columns:
    data[i] = data[i].astype(str).astype(float)

In [12]:
data

,gld_price,gas_price,oil_price,dolla_index,etf_index,silver_price,bitcoin_price
2016-02-19,1231.15,1.83,31.66,113.9502,24.88,15.370,420.785004
2016-02-19,1267.00,1.83,31.66,113.9502,24.88,15.370,420.785004
2016-02-22,1211.00,1.86,33.59,113.8157,23.31,15.000,437.747986
2016-02-23,1221.35,1.85,31.90,114.1686,23.69,15.210,420.735992
2016-02-24,1250.75,1.85,31.50,114.1630,24.24,15.320,424.954987
2016-02-25,1236.00,1.78,32.83,113.9160,23.36,15.160,424.544006
2016-02-26,1226.50,1.78,35.76,114.3650,21.67,15.170,432.152008
2016-02-29,1234.90,1.62,35.92,114.2359,22.59,14.750,437.696991
2016-03-01,1236.50,1.57,35.73,113.9208,21.97,14.990,435.122986
2016-03-02,1239.20,1.60,36.38,113.7902,22.00,14.820,423.989014
2016-03-03,1250.25,1.59,35.75,113.2419,23.51,14.970,421.651001
2016-03-04,1277.50,1.49,37.61,112.6317,22.31,15.430,410.938995
2016-03-07,1267.90,1.56,39.02,112.6166,22.08,15.660,414.321014
2016-03-09,1246.40,1.61,40.26,112.4212,22.31,15.270,414.859985
2016-03-10,1266.50,1.72,38.63,112.4122,23.14,15.270,417.131012
2016-03-11,1264.75,1.74,39.41,111.7351,21.90,15.500,421.690002
2016-03-14,1242.75,1.68,38.06,112.1613,21.14,15.600,416.437988
2016-03-15,1232.00,1.81,37.49,112.5466,19.70,15.320,416.829987
2016-03-16,1228.50,1.77,38.38,112.7674,20.03,15.290,417.010986
2016-03-17,1266.50,1.84,39.29,110.4412,18.99,15.730,420.621002
2016-03-18,1252.10,1.84,39.26,110.3961,18.15,15.940,409.548004
2016-03-21,1244.90,1.79,39.91,110.7310,17.40,15.810,413.307007
2016-03-22,1252.50,1.79,40.54,110.7805,17.62,15.890,418.088989
2016-03-23,1217.60,1.79,38.84,111.5395,18.00,15.580,418.040985
2016-03-24,1221.00,1.78,38.33,111.8078,18.09,15.280,416.394012
2016-03-29,1226.00,1.77,36.75,111.3677,19.52,15.060,416.515991
2016-03-30,1236.25,1.87,36.75,110.2259,18.58,15.380,414.816010
2016-03-31,1237.00,1.98,36.75,109.9138,18.45,15.380,416.729004
2016-04-01,1213.60,1.88,36.42,110.2911,18.04,15.380,417.959991
2016-04-04,1219.75,1.96,36.05,110.3935,17.95,14.960,421.444000
...,...,...,...,...,...,...,...
2020-08-14,1944.75,2.23,44.86,117.3451,23.53,26.705,11768.871094
2020-08-17,1972.85,2.32,44.91,117.1610,26.35,26.915,12254.402344
2020-08-18,2008.75,2.45,45.34,116.9742,26.46,28.325,11991.233398
2020-08-19,1981.00,2.43,45.21,116.9715,28.15,27.440,11758.283203
2020-08-20,1927.15,2.35,44.56,117.2289,25.91,26.915,11878.372070
2020-08-21,1924.35,2.39,43.94,117.4606,25.96,26.850,11592.489258
2020-08-24,1943.95,2.57,44.43,117.3210,23.86,26.885,11774.595703
2020-08-25,1911.15,2.54,46.01,117.2333,22.76,26.495,11366.134766
2020-08-26,1932.95,2.52,45.79,117.0289,24.79,26.395,11488.363281
2020-08-27,1923.85,2.52,44.84,117.0536,23.08,27.245,11323.397461
2020-08-28,1957.35,2.46,45.22,116.3198,23.19,27.350,11542.500000
2020-09-01,1972.35,2.22,45.72,115.9291,23.00,28.885,11970.478516
2020-09-02,1947.05,2.15,42.70,116.3900,23.57,27.705,11414.034180
2020-09-03,1940.45,2.32,42.72,116.4248,23.68,26.900,10245.296875
2020-09-04,1926.30,1.80,41.10,116.3822,21.98,26.815,10511.813477
2020-09-08,1910.95,2.35,38.53,116.8275,22.49,26.675,10131.516602
2020-09-09,1947.20,2.21,39.98,116.4856,21.66,26.535,10242.347656
2020-09-10,1966.25,2.13,39.27,116.2510,21.26,27.105,10363.138672
2020-09-11,1947.40,1.93,38.80,116.4578,20.20,26.875,10400.915039
2020-09-14,1958.70,2.18,38.57,116.0054,20.91,26.885,10680.837891
2020-09-15,1949.35,2.19,39.54,115.9435,20.32,27.545,10796.951172
2020-09-16,1961.80,2.06,41.23,115.6920,20.08,27.380,10974.905273
2020-09-17,1936.25,1.65,42.35,115.7819,19.95,26.745,10948.990234
2020-09-18,1950.85,1.56,42.16,115.5932,20.22,27.060,10944.585938
2020-09-21,1909.35,1.33,40.37,116.7602,21.60,26.360,10462.259766
2020-09-22,1906.00,1.49,40.84,116.9191,21.63,24.300,10538.459961
2020-09-23,1873.40,1.74,41.09,117.6486,23.43,23.595,10225.864258
2020-09-24,1861.75,1.93,41.24,117.9406,23.41,22.220,10745.548828
2020-09-25,1859.70,1.90,40.91,118.2650,22.09,22.630,10702.290039
2020-09-28,1864.30,1.83,41.59,118.0243,22.01,22.890,10721.327148

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1121 entries, 2016-02-19 to 2020-09-28
Data columns (total 7 columns):
gld_price        1121 non-null float64
gas_price        1121 non-null float64
oil_price        1121 non-null float64
dolla_index      1121 non-null float64
etf_index        1121 non-null float64
silver_price     1121 non-null float64
bitcoin_price    1121 non-null float64
dtypes: float64(7)
memory usage: 70.1 KB

In [14]:
data.describe()

,gld_price,gas_price,oil_price,dolla_index,etf_index,silver_price,bitcoin_price
count,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000
mean,1368.480107,2.667038,56.225549,114.305829,14.810803,17.025013,5686.397440
std,188.281445,0.597017,13.381121,3.617708,5.111558,2.352017,3941.998319
min,1125.700000,1.330000,9.120000,106.490700,8.880000,12.005000,409.548004
25%,1250.450000,2.270000,46.730000,111.758800,11.380000,15.580000,1223.540039
50%,1295.450000,2.760000,56.580000,114.535600,13.030000,16.810000,6334.729980
75%,1452.050000,2.980000,65.860000,116.433700,16.800000,17.630000,8827.764648
max,2067.150000,6.240000,86.070000,126.471900,48.980000,28.885000,19114.199219

In [39]:
x = data.drop(columns=[data.columns[i] for i in [0]])
y = data.drop(columns=[data.columns[i] for i in [1,2,3,4,5,6]])

In [40]:
x

,gas_price,oil_price,dolla_index,etf_index,silver_price,bitcoin_price
2016-02-19,1.83,31.66,113.9502,24.88,15.370,420.785004
2016-02-19,1.83,31.66,113.9502,24.88,15.370,420.785004
2016-02-22,1.86,33.59,113.8157,23.31,15.000,437.747986
2016-02-23,1.85,31.90,114.1686,23.69,15.210,420.735992
2016-02-24,1.85,31.50,114.1630,24.24,15.320,424.954987
2016-02-25,1.78,32.83,113.9160,23.36,15.160,424.544006
2016-02-26,1.78,35.76,114.3650,21.67,15.170,432.152008
2016-02-29,1.62,35.92,114.2359,22.59,14.750,437.696991
2016-03-01,1.57,35.73,113.9208,21.97,14.990,435.122986
2016-03-02,1.60,36.38,113.7902,22.00,14.820,423.989014
2016-03-03,1.59,35.75,113.2419,23.51,14.970,421.651001
2016-03-04,1.49,37.61,112.6317,22.31,15.430,410.938995
2016-03-07,1.56,39.02,112.6166,22.08,15.660,414.321014
2016-03-09,1.61,40.26,112.4212,22.31,15.270,414.859985
2016-03-10,1.72,38.63,112.4122,23.14,15.270,417.131012
2016-03-11,1.74,39.41,111.7351,21.90,15.500,421.690002
2016-03-14,1.68,38.06,112.1613,21.14,15.600,416.437988
2016-03-15,1.81,37.49,112.5466,19.70,15.320,416.829987
2016-03-16,1.77,38.38,112.7674,20.03,15.290,417.010986
2016-03-17,1.84,39.29,110.4412,18.99,15.730,420.621002
2016-03-18,1.84,39.26,110.3961,18.15,15.940,409.548004
2016-03-21,1.79,39.91,110.7310,17.40,15.810,413.307007
2016-03-22,1.79,40.54,110.7805,17.62,15.890,418.088989
2016-03-23,1.79,38.84,111.5395,18.00,15.580,418.040985
2016-03-24,1.78,38.33,111.8078,18.09,15.280,416.394012
2016-03-29,1.77,36.75,111.3677,19.52,15.060,416.515991
2016-03-30,1.87,36.75,110.2259,18.58,15.380,414.816010
2016-03-31,1.98,36.75,109.9138,18.45,15.380,416.729004
2016-04-01,1.88,36.42,110.2911,18.04,15.380,417.959991
2016-04-04,1.96,36.05,110.3935,17.95,14.960,421.444000
...,...,...,...,...,...,...
2020-08-14,2.23,44.86,117.3451,23.53,26.705,11768.871094
2020-08-17,2.32,44.91,117.1610,26.35,26.915,12254.402344
2020-08-18,2.45,45.34,116.9742,26.46,28.325,11991.233398
2020-08-19,2.43,45.21,116.9715,28.15,27.440,11758.283203
2020-08-20,2.35,44.56,117.2289,25.91,26.915,11878.372070
2020-08-21,2.39,43.94,117.4606,25.96,26.850,11592.489258
2020-08-24,2.57,44.43,117.3210,23.86,26.885,11774.595703
2020-08-25,2.54,46.01,117.2333,22.76,26.495,11366.134766
2020-08-26,2.52,45.79,117.0289,24.79,26.395,11488.363281
2020-08-27,2.52,44.84,117.0536,23.08,27.245,11323.397461
2020-08-28,2.46,45.22,116.3198,23.19,27.350,11542.500000
2020-09-01,2.22,45.72,115.9291,23.00,28.885,11970.478516
2020-09-02,2.15,42.70,116.3900,23.57,27.705,11414.034180
2020-09-03,2.32,42.72,116.4248,23.68,26.900,10245.296875
2020-09-04,1.80,41.10,116.3822,21.98,26.815,10511.813477
2020-09-08,2.35,38.53,116.8275,22.49,26.675,10131.516602
2020-09-09,2.21,39.98,116.4856,21.66,26.535,10242.347656
2020-09-10,2.13,39.27,116.2510,21.26,27.105,10363.138672
2020-09-11,1.93,38.80,116.4578,20.20,26.875,10400.915039
2020-09-14,2.18,38.57,116.0054,20.91,26.885,10680.837891
2020-09-15,2.19,39.54,115.9435,20.32,27.545,10796.951172
2020-09-16,2.06,41.23,115.6920,20.08,27.380,10974.905273
2020-09-17,1.65,42.35,115.7819,19.95,26.745,10948.990234
2020-09-18,1.56,42.16,115.5932,20.22,27.060,10944.585938
2020-09-21,1.33,40.37,116.7602,21.60,26.360,10462.259766
2020-09-22,1.49,40.84,116.9191,21.63,24.300,10538.459961
2020-09-23,1.74,41.09,117.6486,23.43,23.595,10225.864258
2020-09-24,1.93,41.24,117.9406,23.41,22.220,10745.548828
2020-09-25,1.90,40.91,118.2650,22.09,22.630,10702.290039
2020-09-28,1.83,41.59,118.0243,22.01,22.890,10721.327148

In [41]:
y

            gld_price
2016-02-19    1231.15
2016-02-19    1267.00
2016-02-22    1211.00
2016-02-23    1221.35
2016-02-24    1250.75
2016-02-25    1236.00
2016-02-26    1226.50
2016-02-29    1234.90
2016-03-01    1236.50
2016-03-02    1239.20
2016-03-03    1250.25
2016-03-04    1277.50
2016-03-07    1267.90
2016-03-09    1246.40
2016-03-10    1266.50
2016-03-11    1264.75
2016-03-14    1242.75
2016-03-15    1232.00
2016-03-16    1228.50
2016-03-17    1266.50
2016-03-18    1252.10
2016-03-21    1244.90
2016-03-22    1252.50
2016-03-23    1217.60
2016-03-24    1221.00
2016-03-29    1226.00
2016-03-30    1236.25
2016-03-31    1237.00
2016-04-01    1213.60
2016-04-04    1219.75
...               ...
2020-08-14    1944.75
2020-08-17    1972.85
2020-08-18    2008.75
2020-08-19    1981.00
2020-08-20    1927.15
2020-08-21    1924.35
2020-08-24    1943.95
2020-08-25    1911.15
2020-08-26    1932.95
2020-08-27    1923.85
2020-08-28    1957.35
2020-09-01    1972.35
2020-09-02    1947.05
2020-09-03    1940.45
2020-09-04    1926.30
2020-09-08    1910.95
2020-09-09    1947.20
2020-09-10    1966.25
2020-09-11    1947.40
2020-09-14    1958.70
2020-09-15    1949.35
2020-09-16    1961.80
2020-09-17    1936.25
2020-09-18    1950.85
2020-09-21    1909.35
2020-09-22    1906.00
2020-09-23    1873.40
2020-09-24    1861.75
2020-09-25    1859.70
2020-09-28    1864.30

[1121 rows x 1 columns]

In [42]:
x = x.apply(lambda a: preprocessing.MinMaxScaler().fit_transform(a))

ValueError: ('Expected 2D array, got 1D array instead:\narray=[1.83 1.83 1.86 ... 1.93 1.9  1.83].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.', 'occurred at index gas_price')

In [43]:
min_max_scaler = preprocessing.MinMaxScaler()
scaled_df = scaleColumns(x,x.columns)

In [44]:
scaled_df

,gas_price,oil_price,dolla_index,etf_index,silver_price,bitcoin_price
2016-02-19,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-19,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-22,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-23,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-24,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-25,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-26,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-29,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-01,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-02,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-03,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-04,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-07,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-09,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-10,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-11,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-14,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-15,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-16,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-17,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-18,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-21,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-22,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-23,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-24,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-29,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-30,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-31,NaN,NaN,NaN,NaN,NaN,NaN
2016-04-01,NaN,NaN,NaN,NaN,NaN,NaN
2016-04-04,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2020-08-14,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-17,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-19,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-20,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-21,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-24,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-25,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-26,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-27,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-28,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-01,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-02,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-03,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-04,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-08,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-09,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-10,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-11,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-14,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-15,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-16,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-17,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-18,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-21,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-22,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-23,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-24,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-25,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-28,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

In [48]:
x_train

,gas_price,oil_price,dolla_index,etf_index,silver_price,bitcoin_price
2019-10-17,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-18,NaN,NaN,NaN,NaN,NaN,NaN
2016-04-06,NaN,NaN,NaN,NaN,NaN,NaN
2019-11-25,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-24,NaN,NaN,NaN,NaN,NaN,NaN
2019-06-05,NaN,NaN,NaN,NaN,NaN,NaN
2016-08-18,NaN,NaN,NaN,NaN,NaN,NaN
2019-11-07,NaN,NaN,NaN,NaN,NaN,NaN
2020-05-18,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-12,NaN,NaN,NaN,NaN,NaN,NaN
2019-06-20,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-18,NaN,NaN,NaN,NaN,NaN,NaN
2019-07-18,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-29,NaN,NaN,NaN,NaN,NaN,NaN
2016-10-03,NaN,NaN,NaN,NaN,NaN,NaN
2018-09-04,NaN,NaN,NaN,NaN,NaN,NaN
2017-09-28,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-21,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-24,NaN,NaN,NaN,NaN,NaN,NaN
2016-06-30,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-04,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-16,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-13,NaN,NaN,NaN,NaN,NaN,NaN
2019-06-04,NaN,NaN,NaN,NaN,NaN,NaN
2016-05-13,NaN,NaN,NaN,NaN,NaN,NaN
2016-04-19,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-05,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-17,NaN,NaN,NaN,NaN,NaN,NaN
2017-10-30,NaN,NaN,NaN,NaN,NaN,NaN
2019-08-01,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2019-08-08,NaN,NaN,NaN,NaN,NaN,NaN
2018-06-28,NaN,NaN,NaN,NaN,NaN,NaN
2019-07-31,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-25,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-17,NaN,NaN,NaN,NaN,NaN,NaN
2017-04-26,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-06,NaN,NaN,NaN,NaN,NaN,NaN
2016-12-30,NaN,NaN,NaN,NaN,NaN,NaN
2017-09-06,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-14,NaN,NaN,NaN,NaN,NaN,NaN
2018-03-13,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-27,NaN,NaN,NaN,NaN,NaN,NaN
2016-04-18,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-10,NaN,NaN,NaN,NaN,NaN,NaN
2016-02-22,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-19,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-17,NaN,NaN,NaN,NaN,NaN,NaN
2018-08-14,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-02,NaN,NaN,NaN,NaN,NaN,NaN
2019-08-13,NaN,NaN,NaN,NaN,NaN,NaN
2016-08-01,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-18,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,NaN,NaN,NaN,NaN,NaN,NaN
2016-06-07,NaN,NaN,NaN,NaN,NaN,NaN
2016-04-28,NaN,NaN,NaN,NaN,NaN,NaN
2018-09-27,NaN,NaN,NaN,NaN,NaN,NaN
2016-08-03,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-11,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-25,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-03,NaN,NaN,NaN,NaN,NaN,NaN